const mongoose = require('mongoose');

const launchPadSchema = mongoose.Schema({
    userId: { type: mongoose.Types.ObjectId, ref: 'user' },
    name: { type: String, default: "" },
    email: { type: String, default: "" },
    position: { type: String, default: "" },
    refemail: { type: String, default: "" },
    project_name: { type: String, default: "" },
    official_website: { type: String, default: "" },
    Project_description: { type: String, default: "" },
    Project_banner: { type: String, default: "" },
    token_feature: { type: String, default: "" },
    token_supply: { type: String, default: "" },
    symbol: { type: String, default: "" },  
    currency_name: { type: String, default: "" },
    whitepaper_link: { type: String, default: "" },
    milestone: { type: String, default: "" },
    contract_address: { type: String, default: "" },
    address_type: { type: String, default: "" },
    currency_image: { type: String, default: "" },
    description: { type: String, default: "" },
    network: { type: String, default: "" },
    startDate: { type: Date, default: "" },
    endDate: { type: Date, default: "" },
    buyAmount: { type: Number, default: "" },
    softCap: { type: Number, default: 0 },
    hardCap: { type: Number, default: 0 },
    totalSupply: { type: Number, default: 0 },
    price: { type: Number, default: 0 },
    telegram: { type: String, default: "" },
    instagramlink: { type: String, default: "" },
    twitterLink: { type: String, default: "" },
    youtubeChannel: { type: String, default: "" },
    Youtube_video: { type: String, default: "" },
    startDate: { type: Date, default: "" },
    endDate: { type: Date, default: "" },
    terms: { type: String, default: "" },
    status: { type: Number, default: 0 },
    created_at: { type: Date, default: Date.now() },
    updated_at: { type: Date, default: Date.now() },
});

module.exports = mongoose.model('launchPad', launchPadSchema, 'launchPad');